[assembly: System.Reflection.AssemblyCompany("Renowned Games")]
[assembly: System.Reflection.AssemblyTitle("ExLibEditor")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2022 Tamerlan Shakirov All rights reserved.")]
[assembly: UnityEngine.Scripting.Preserve]
